spring:
  application:
    name: app02
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}-${server.port}
server:
  port: 8082

artifactId: @artifactId@
