spring:
  application:
    name: app01
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}-${server.port}
        health-check-path: /demo/demo.do
server:
  port: 8081